fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    yumrepo_core: 
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: ">= 6.0.0"
    augeas_core: 
      repo: "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
      puppet_version: ">= 6.0.0"
  symlinks:
    postgresql: "#{source_dir}"
